### ISSUE TITLE
link error in API Specs document

### ISSUE THREAD

**Issue by maple10001** [Azure/iothub-manager-dotnet#100]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

- link to Get single device is not correct in API Spec document

# Steps to reproduce

1. Go to API Spec Wiki
2. Click on link shown below

![image](https://user-images.githubusercontent.com/8744187/31524300-7d86a8ca-af6d-11e7-939f-f5541669a5d8.png)

**Comment by xzsheng** [comment]
Fixed
