### ISSUE TITLE
get single Job 200 response does not contain "Devices"

### ISSUE THREAD

**Issue by maple10001** [Azure/iothub-manager-dotnet#101]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

- get single Job 200 response does not contain "Devices"

# Steps to reproduce

1.  ```GET /v1/jobs/{id}```

# Expected behavior

- ```GET /v1/jobs/{id}``` returns job object as described in [https://github.com/Azure/iothub-manager-dotnet/wiki/API-Specs#get-job-status-by-job-id](url)

# Current behavior

- ```GET /v1/jobs/{id}``` returns job object does not match API specs

**Comment by xzsheng** [comment]
@maple10001, could you please share more detail to repro this issue? Thanks.

Reminder: The item `Devices` will only be available for completed or failed device method job. In other words, there will no such an item if the job is a twin update job, or the device method job was just queued or running.

**Comment by maple10001** [comment]
@xzsheng works with query param ```?includeDeviceDetails=true```
