### ISSUE TITLE
The properties `endTimeUtc` in model `JobResponse` is not correct

### ISSUE THREAD

**Issue by maple10001** [Azure/iothub-manager-dotnet#108]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
The properties `endTimeUtc` in model `JobResponse` is not correct
`endTimeUtc: "0001-01-01T00:00:00Z" `

# Steps to reproduce 

1. create a job
2. get job 

# Expected behavior 
- return correct time

# Current behavior <!-- The actual behavior observed --
-  `endTimeUtc: "0001-01-01T00:00:00Z" `

**Comment by timlaverty** [comment]
Is this an SDK problem; i.e. is the data coming back incorrect? ...or are we formatting it incorrectly when returning through the api?

**Comment by maple10001** [comment]
Correct time returned after status change to complete. Close as not an issue.
