### ISSUE TITLE
The properties `deviceJobStatus`  in model `JobResponse` always `3 - completed`

### ISSUE THREAD

**Issue by maple10001** [Azure/iothub-manager-dotnet#109]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
`GET /v1/jobs/{id}?includeDeviceDetails=true`

The properties `deviceJobStatus` in model `JobResponse` always `3 - completed` 
...

# Expected behavior 
``deviceJobStatus`` should reflect the state of status

# Current behavior <!-- The actual behavior observed --
``deviceJobStatus`` always in state of  `3 - completed`

**Comment by xzsheng** [comment]
@maple10001 please share more details about how to repro this issue.

Btw, I tried to schedule a method job with incorrect query condition. The status DID switched from 2 - Running to 4 - Failed. Here are the two response clips:

```
...
    {
        "jobId": "xzshengTestJob102501",
        "queryCondition": "deviceId is me",
        "createdTimeUtc": "2017-10-25T02:53:20.7024529Z",
        "startTimeUtc": "2017-10-25T02:53:19.1360874",
        "endTimeUtc": "9999-12-30T23:59:59.9999999Z",
        "maxExecutionTimeInSeconds": 3600,
        "type": 3,
        "status": 2,
        "methodParameter": {
            "name": "Reboot",
            "responseTimeout": "00:00:00",
            "connectionTimeout": "00:00:00",
            "jsonPayload": "null"
        }
    },
...
```

```
...
    {
        "jobId": "xzshengTestJob102501",
        "queryCondition": "deviceId is me",
        "createdTimeUtc": "2017-10-25T02:53:20.7024529Z",
        "startTimeUtc": "2017-10-25T02:53:19.1360874",
        "endTimeUtc": "2017-10-25T02:54:08.1262009Z",
        "maxExecutionTimeInSeconds": 3600,
        "type": 3,
        "status": 4,
        "methodParameter": {
            "name": "Reboot",
            "responseTimeout": "00:00:00",
            "connectionTimeout": "00:00:00",
            "jsonPayload": "null"
        },
        "failureReason": "Failure message: 'SQL query parse failed due to following errors: \n\tLine 1:37 mismatched input 'is' expecting {'.', COMPARISON_OPERATOR}'. Query: 'SELECT * FROM devices WHERE deviceId is me'"
    },
...
```

Reminder: status 3 - Completed means IoTHub completed to send command to devices, regardless the per device result. Even all targeting devices were not online, or no targeting device at all, it will be 3 - Completed.

**Comment by xzsheng** [comment]
@maple10001 device job status (Devices/Status) means whether IoTHub successfully send command to given single device. While the job status (status) means whether IoTHub complete the whole command for all devices. So it is expected that some device job status become "completed" before the whole job status become "completed".

For the reason job status is 7 - queued, I guess it was caused by some delay in IoTHub service itself. Could you please try to call the same API for some times to check if the status will become "running" and then "completed"?

**Comment by maple10001** [comment]
@xzsheng `job status` updated correctly. Closing the issue.
