### ISSUE TITLE
What is the value for PCS_CONFIG_WEBSERVICE_URL?

### ISSUE THREAD

**Issue by isharehappycode** [Azure/iothub-manager-dotnet#121]

**Comment by dluc** [comment]
If you're running the service locally, you'll have to start the [Configuration microservice](https://github.com/azure/pcs-config-dotnet), which by default runs on port 9005.  
So the value of `PCS_CONFIG_WEBSERVICE_URL` will be `http://127.0.0.1:9005/v1`

**Comment by dluc** [comment]
@ppathan looks like the microservice docs don't have this information

**Comment by ppathan** [comment]
`PCS_CONFIG_WEBSERVICE_URL` dependency has been removed
